const PDFDocument = require('pdfkit');

/**
 * Generates a professional PDF prescription document and writes it to the output stream.
 * @param {Object} data - Joined database row containing prescription and patient details
 * @param {WritableStream} outputStream - Express response object or file stream
 */
function generatePrescriptionPDF(data, outputStream) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  // Pipe to response/file stream
  doc.pipe(outputStream);

  // Colors
  const primaryColor = '#10B981'; // Emerald Green
  const darkNeutral = '#1E293B';  // slate 800
  const lightNeutral = '#F8FAFC'; // slate 50
  const accentColor = '#64748B';  // slate 500

  // 1. HEADER BRANDING
  doc.rect(0, 0, 595.28, 120).fill(primaryColor);
  
  doc.fillColor('#FFFFFF')
     .fontSize(24)
     .font('Helvetica-Bold')
     .text('🏥 SACRED HEART MEDICAL CENTER', 50, 35)
     .fontSize(10)
     .font('Helvetica')
     .text('12-3-45, Beach Road, Pandurangapuram, Visakhapatnam - 530003 | Tel: +91 891 234 5678', 50, 70)
     .text('Email: care@sacredheart.com | Web: www.sacredheartmedical.com', 50, 85);

  // 2. METADATA BLOCK (Doctor & Rx Info)
  doc.fillColor(darkNeutral);
  
  // Left: Doctor Info
  doc.fontSize(12)
     .font('Helvetica-Bold')
     .text('PRESCRIBING PHYSICIAN', 50, 150)
     .font('Helvetica')
     .fontSize(14)
     .text(data.doctor_name, 50, 168)
     .fontSize(10)
     .fillColor(accentColor)
     .text(`${data.specialization} (${data.department_name || 'General Medicine'})`, 50, 185);

  // Right: Prescription Metadata
  doc.fillColor(darkNeutral);
  doc.fontSize(12)
     .font('Helvetica-Bold')
     .text('PRESCRIPTION DETAILS', 380, 150)
     .font('Helvetica')
     .fontSize(10)
     .text(`Rx ID: RX-2026-${String(data.prescription_id).padStart(4, '0')}`, 380, 168)
     .text(`Date: ${new Date(data.visit_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 380, 182)
     .text(`Record ID: REC-${String(data.record_id).padStart(4, '0')}`, 380, 196);

  // Divider Line
  doc.moveTo(50, 220).lineTo(545, 220).strokeColor('#E2E8F0').lineWidth(1).stroke();

  // 3. PATIENT INFO
  doc.fillColor(darkNeutral)
     .fontSize(12)
     .font('Helvetica-Bold')
     .text('PATIENT INFORMATION', 50, 235);

  // Patient Card background
  doc.rect(50, 250, 495, 55).fill(lightNeutral);
  
  doc.fillColor(darkNeutral)
     .fontSize(10)
     .font('Helvetica-Bold')
     .text('Name:', 65, 262).font('Helvetica').text(data.patient_name, 110, 262)
     .font('Helvetica-Bold').text('Age / Gender:', 65, 282).font('Helvetica').text(`${data.age || 'N/A'} yrs / ${data.gender || 'N/A'}`, 140, 282)
     .font('Helvetica-Bold').text('Blood Group:', 320, 262).font('Helvetica').text(data.blood_group || 'N/A', 395, 262);

  // Divider Line
  doc.moveTo(50, 320).lineTo(545, 320).strokeColor('#E2E8F0').lineWidth(1).stroke();

  // 4. DIAGNOSIS
  doc.fillColor(darkNeutral)
     .fontSize(12)
     .font('Helvetica-Bold')
     .text('DIAGNOSIS & CLINICAL NOTES', 50, 335)
     .font('Helvetica')
     .fontSize(10)
     .text(data.diagnosis, 50, 355, { width: 495, align: 'justify' });

  if (data.treatment) {
    doc.font('Helvetica-Bold')
       .text('Recommended Treatment Plan:', 50, 385)
       .font('Helvetica')
       .text(data.treatment, 50, 400, { width: 495, align: 'justify' });
  }

  // Divider Line
  doc.moveTo(50, 435).lineTo(545, 435).strokeColor('#E2E8F0').lineWidth(1).stroke();

  // 5. MEDICATIONS (Rx)
  doc.fillColor(darkNeutral)
     .fontSize(16)
     .font('Helvetica-Bold')
     .text('Rx (Prescription)', 50, 455);

  // Medicine list block
  doc.font('Helvetica-Bold')
     .fontSize(11)
     .text('Medicine / Drug Name', 50, 485)
     .text('Dosage', 250, 485)
     .text('Duration', 380, 485);

  doc.moveTo(50, 500).lineTo(545, 500).strokeColor('#CBD5E1').lineWidth(0.75).stroke();

  doc.font('Helvetica')
     .fontSize(10)
     .text(data.medicines, 50, 515, { width: 180 })
     .text(data.dosage || 'As directed', 250, 515, { width: 120 })
     .text(data.duration || 'As needed', 380, 515, { width: 150 });

  if (data.instructions) {
    doc.fillColor('#475569')
       .font('Helvetica-Oblique')
       .fontSize(9)
       .text(`Instructions: ${data.instructions}`, 50, 550, { width: 495 });
  }

  // Divider Line
  doc.moveTo(50, 620).lineTo(545, 620).strokeColor('#E2E8F0').lineWidth(1).stroke();

  // 6. SIGNATURE & FOOTER
  doc.fillColor(darkNeutral)
     .font('Helvetica-Bold')
     .fontSize(10)
     .text('Physician Signature:', 350, 660)
     .moveTo(350, 710).lineTo(520, 710).strokeColor('#94A3B8').lineWidth(1).stroke()
     .font('Helvetica')
     .fontSize(8)
     .fillColor(accentColor)
     .text('This prescription is dynamically generated by the Sacred Heart EMR portal.', 50, 740)
     .text('Please consult a pharmacist if you experience any adverse effects.', 50, 752)
     .text('Page 1 of 1', 500, 740);

  // Finalize document
  doc.end();
}

module.exports = {
  generatePrescriptionPDF,
};
